services:
  rparliament:
    build:
      context: .
    depends_on:
      - fluentbit
    restart: unless-stopped
    ports:
      - "4141:4141"
      - "8282:8282"
    volumes:
      - ./keys/root.crt:/etc/ssl/certs/root.crt:ro
      - ./keys/node.crt:/etc/ssl/certs/node.crt:ro
      - ./keys/node.key:/etc/ssl/private/node.key:ro
      - ./config/peers.lst:/data/out/share/peers.lst
    environment:
      NODENAME: ${NODENAME}
    logging:
      driver: fluentd
      options:
        fluentd-address: "127.0.0.1:24224"
        fluentd-async: "true"

  fluentbit:
    image: fluent/fluent-bit:4.2.1
    restart: unless-stopped
    ports:
      - "127.0.0.1:24224:24224"
      - "127.0.0.1:24224:24224/udp"
    volumes:
      - fluentbit_buffer:/fluent-bit/storage
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro

      - ./keys/node.crt:/etc/ssl/certs/node.crt:ro
      - ./keys/node.key:/etc/ssl/private/node.key:ro
      - ./keys/root.crt:/etc/ssl/certs/root.crt:ro
    environment:
      - "TAG=rparliament.${NODENAME}"

volumes:
  fluentbit_buffer:
